# 1. Write a NumPy program to sort a given array by row and column in ascending order.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10,25,16).reshape(4,4)

In [3]:
arr

array([[22, 20, 10, 23],
       [10, 24, 13, 18],
       [18, 24, 19, 16],
       [23, 15, 23, 13]])

In [4]:
#column ascending order
np.sort(arr,axis = 0)

array([[10, 15, 10, 13],
       [18, 20, 13, 16],
       [22, 24, 19, 18],
       [23, 24, 23, 23]])

In [5]:
#row ascending order
np.sort(arr,axis=1)

array([[10, 20, 22, 23],
       [10, 13, 18, 24],
       [16, 18, 19, 24],
       [13, 15, 23, 23]])

# 2. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [9]:
arr_3d = np.random.randint(0,100,3*5*4).reshape(3,5,4)

In [10]:
arr_3d

array([[[75, 59, 17, 20],
        [ 7, 46, 82, 38],
        [31,  5, 56, 35],
        [65, 68,  6, 80],
        [ 2, 42, 36,  4]],

       [[40, 44, 27, 49],
        [38, 95, 96, 49],
        [90, 47, 22,  3],
        [ 3, 31, 86, 98],
        [17, 81, 49, 26]],

       [[78, 39, 92, 71],
        [79,  3, 97, 13],
        [33, 91,  8, 34],
        [88, 72, 28, 94],
        [86, 96, 44, 35]]])

In [11]:
arr_3d.shape

(3, 5, 4)

# 3.  Write a NumPy program to swap rows and columns of a given array in reverse order.Write a NumPy program to multiply two given arrays of same size element-by-element.

In [13]:
arr_1 = np.random.randint(10,100,20).reshape(4,5)
arr_2 = np.random.randint(20,80,20).reshape(4,5)

In [14]:
arr_1

array([[30, 72, 85, 79, 12],
       [31, 72, 80, 35, 31],
       [17, 51, 61, 11, 79],
       [65, 48, 32, 20, 21]])

In [15]:
#swapping
np.transpose(arr_1)

array([[30, 31, 17, 65],
       [72, 72, 51, 48],
       [85, 80, 61, 32],
       [79, 35, 11, 20],
       [12, 31, 79, 21]])

In [16]:
#multiplication element by element
arr_1*arr_2

array([[ 600, 3312, 5865, 4661,  372],
       [ 620, 5472, 1760, 1995, 1209],
       [ 714, 4029, 4636,  858, 2607],
       [2015, 2976,  864, 1340,  504]])

# 4. Write a NumPy program to print the NumPy version in your system.

In [17]:
np.__version__

'1.21.5'

# 5. Print max from axis 0 and min from axis 1 from the following 2-D array.
sampleArray =
numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [18]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [19]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [20]:
np.max(sampleArray,axis=0)

array([82, 94, 73])

In [21]:
np.min(sampleArray,axis=1)

array([34, 12, 53])

# 6. Delete the second column from a given array and insert the following new column in its place.
sampleArray =
numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

In [23]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

In [30]:
new_arr = np.delete(sampleArray, 1,axis = 1)

In [38]:
new_arr

array([[34, 73],
       [82, 12],
       [53, 66]])

In [37]:
np.insert(new_arr, 1, newColumn,  axis = 1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

# 7. Sort following NumPy array
● Case 1: Sort array by the second row

● Case 2: Sort the array by the second column

sampleArray =
numpy.array([[34,43,73],[82,22,12],[53,94,66]])


In [40]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [41]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [56]:
#case 1
c = sampleArray[1,:].argsort()
c

array([2, 1, 0], dtype=int64)

In [58]:
sampleArray[:,c]

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [54]:
#case 2
c1 = sampleArray[:,1].argsort()
c1

array([1, 0, 2], dtype=int64)

In [55]:
sampleArray[c1]

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

# 8. Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])

arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [59]:
arr_1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr_2 = np.array([[15 ,33, 24], [4 ,7, 1]])

In [60]:
sum_arr = arr_1 + arr_2

In [61]:
sum_arr

array([[20, 39, 33],
       [25, 25, 28]])

In [63]:
##square of each element
np.square(sum_arr)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

# 9. Write a NumPy program to compute the multiplication of two given matrixes.


In [65]:
arr1 = np.random.randint(0,25,6).reshape(2,3)
arr2 = np.random.randint(0,25,6).reshape(2,3)

In [66]:
arr1

array([[16, 13, 18],
       [ 9,  1,  9]])

In [67]:
arr2 

array([[13,  1, 21],
       [10, 20,  4]])

In [69]:
np.dot(arr1,arr2.T)

array([[599, 492],
       [307, 146]])

# 10. Write a NumPy program to find a matrix or vector norm.


In [70]:
arr = np.random.randint(4,25,9).reshape(3,3)

In [71]:
arr

array([[22, 24, 20],
       [19,  4, 15],
       [15, 10, 13]])

In [72]:
np.linalg.norm(arr)

50.556898639058154