In [1]:
import numpy as np

# 1. Write a NumPy program to compute the condition number of a given matrix.


In [2]:
arr = np.random.randint(10,30,15).reshape(3,5)

In [3]:
arr

array([[21, 19, 11, 26, 23],
       [18, 23, 26, 11, 13],
       [23, 18, 26, 10, 23]])

In [4]:
np.linalg.cond(arr)

9.443172072768514

# 2. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [5]:
arr1 = np.random.randint(0,100,25).reshape(5,5)
arr2 = np.random.randint(0,100,25).reshape(5,5)

In [6]:
arr1

array([[60, 58, 72, 29, 80],
       [80, 94, 50, 86, 77],
       [63, 90, 20, 39, 67],
       [ 2, 81,  4, 24, 71],
       [93, 59, 47, 82, 55]])

In [7]:
arr2

array([[47,  8, 83, 74, 99],
       [ 7, 56, 37, 90,  3],
       [85, 41, 90, 16, 24],
       [24, 67, 91, 77, 54],
       [30, 75, 17, 24, 83]])

In [8]:
#addition
arr1+arr2

array([[107,  66, 155, 103, 179],
       [ 87, 150,  87, 176,  80],
       [148, 131, 110,  55,  91],
       [ 26, 148,  95, 101, 125],
       [123, 134,  64, 106, 138]])

In [9]:
#subtraction
arr1-arr2

array([[ 13,  50, -11, -45, -19],
       [ 73,  38,  13,  -4,  74],
       [-22,  49, -70,  23,  43],
       [-22,  14, -87, -53,  17],
       [ 63, -16,  30,  58, -28]])

In [10]:
#multiplication
arr1*arr2

array([[2820,  464, 5976, 2146, 7920],
       [ 560, 5264, 1850, 7740,  231],
       [5355, 3690, 1800,  624, 1608],
       [  48, 5427,  364, 1848, 3834],
       [2790, 4425,  799, 1968, 4565]])

In [15]:
#division
np.round(arr1/arr2,3)

array([[ 1.277,  7.25 ,  0.867,  0.392,  0.808],
       [11.429,  1.679,  1.351,  0.956, 25.667],
       [ 0.741,  2.195,  0.222,  2.438,  2.792],
       [ 0.083,  1.209,  0.044,  0.312,  1.315],
       [ 3.1  ,  0.787,  2.765,  3.417,  0.663]])

# 3.  Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.

In [16]:
arr = np.random.randint(20,50,12).reshape(4,3)

In [17]:
arr

array([[24, 31, 22],
       [31, 31, 47],
       [25, 29, 40],
       [39, 24, 48]])

In [18]:
np.floor_divide(arr, 10)

array([[2, 3, 2],
       [3, 3, 4],
       [2, 2, 4],
       [3, 2, 4]], dtype=int32)

# 4. Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array


In [19]:
arr1 = np.array([0,1,2,3,4,5])
arr2 = np.array([3,3,3,3,3,3])

In [20]:
arr1

array([0, 1, 2, 3, 4, 5])

In [21]:
arr1**arr2

array([  0,   1,   8,  27,  64, 125], dtype=int32)

# 5. Write a NumPy program to round array elements to the given number of decimals.


In [22]:
arr = np.random.random(15)
arr

array([0.94967189, 0.44704199, 0.15257671, 0.66790867, 0.56152798,
       0.8917925 , 0.95087648, 0.94795159, 0.76473808, 0.41326256,
       0.65072946, 0.15986799, 0.74439776, 0.84420717, 0.44644357])

In [24]:
#round the value till to 3 decimal places
np.round(arr,3)

array([0.95 , 0.447, 0.153, 0.668, 0.562, 0.892, 0.951, 0.948, 0.765,
       0.413, 0.651, 0.16 , 0.744, 0.844, 0.446])

# 6. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.


In [26]:
arr1 = np.random.randint(0,100,15).reshape(5,3)
arr1

array([[28, 24, 52],
       [94, 84, 76],
       [49, 38,  7],
       [51, 12, 12],
       [10, 33, 40]])

In [27]:
arr2 = np.random.randint(0,100,6).reshape(3,2)
arr2

array([[73, 47],
       [69, 20],
       [67, 69]])

In [28]:
np.dot(arr1,arr2)

array([[ 7184,  5384],
       [17750, 11342],
       [ 6668,  3546],
       [ 5355,  3465],
       [ 5687,  3890]])

# 7. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [29]:
arr = np.random.randint(25,50,15).reshape(3,5)
arr

array([[48, 47, 28, 42, 48],
       [27, 27, 31, 30, 26],
       [26, 26, 42, 31, 33]])

In [30]:
np.sort(arr,axis=0)

array([[26, 26, 28, 30, 26],
       [27, 27, 31, 31, 33],
       [48, 47, 42, 42, 48]])

In [31]:
np.sort(arr,axis=1)

array([[28, 42, 47, 48, 48],
       [26, 27, 27, 30, 31],
       [26, 26, 31, 33, 42]])

In [32]:
np.sort(arr,axis=None)


array([26, 26, 26, 27, 27, 28, 30, 31, 31, 33, 42, 42, 47, 48, 48])

# 8. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

In [40]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]

In [42]:
std_det = [('James', 5, 48.5 ), ('Nail', 6, 52.5 ), ('Paul', 5, 42.1 ), ('Pit', 5,
40.11)]

In [43]:
arr = np.array(std_det, dtype = data_type)

In [44]:
arr

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [47]:
np.sort(arr,order = 'height')

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

# 9. Write a NumPy program to sort an given array by the nth column.


In [49]:
arr = np.array([[1, 5, 0],[3, 2, 5],[8, 7, 6]])
arr

array([[1, 5, 0],
       [3, 2, 5],
       [8, 7, 6]])

In [55]:
arr[arr[:,1].argsort()]

array([[1, 2, 0],
       [3, 5, 5],
       [8, 7, 6]])

# 10. Write a NumPy program to sort the specified number of elements from beginning of a given array

In [56]:
arr = np.random.random(20)
arr

array([0.15507126, 0.30259236, 0.67940196, 0.4806076 , 0.48255157,
       0.45941534, 0.02856099, 0.50750464, 0.97231319, 0.42512278,
       0.25538898, 0.99417012, 0.07504536, 0.04260192, 0.70718997,
       0.60535966, 0.04351114, 0.2835624 , 0.82148151, 0.5837811 ])

sort for first 6 elements

In [60]:
arr_1 = arr[:6]
arr_1

array([0.15507126, 0.30259236, 0.67940196, 0.4806076 , 0.48255157,
       0.45941534])

In [61]:
arr_1 = np.sort(arr_1)

In [62]:
arr_1

array([0.15507126, 0.30259236, 0.45941534, 0.4806076 , 0.48255157,
       0.67940196])

In [65]:
np.concatenate((arr_1,arr[6:]))

array([0.15507126, 0.30259236, 0.45941534, 0.4806076 , 0.48255157,
       0.67940196, 0.02856099, 0.50750464, 0.97231319, 0.42512278,
       0.25538898, 0.99417012, 0.07504536, 0.04260192, 0.70718997,
       0.60535966, 0.04351114, 0.2835624 , 0.82148151, 0.5837811 ])