# Q1. Here's the scenario: You just graded your students on a recent test. Unfortunately, the test was too challenging, and most students did worse than expected. In order to help everyone out, you will curve everyone's grades.
The curve will be relatively simple, however. Taking the average score, you will declare it a C.
However, you should ensure that the curve doesn't accidentally hurt your students' grades or
help them so much that they do better than 100%.
Write a python program using numpy to curve the grades for a number of students.

In [1]:
import numpy as np

In [3]:
student_marks = np.random.randint(0,100,20)

In [4]:
student_marks

array([ 0,  6, 77, 74, 17, 76,  3, 57, 86, 88, 94, 66, 18, 48, 64, 54, 65,
       47,  8, 23])

In [6]:
avg_marks = np.mean(student_marks)

In [7]:
avg_marks 

48.55

In [9]:
marks = []
for i in student_marks:
    sum_marks = i + avg_marks
    if sum_marks>100:
        marks.append(100)
    else:
        marks.append(sum_marks)

In [11]:
marks = np.array(marks)
marks

array([ 48.55,  54.55, 100.  , 100.  ,  65.55, 100.  ,  51.55, 100.  ,
       100.  , 100.  , 100.  , 100.  ,  66.55,  96.55, 100.  , 100.  ,
       100.  ,  95.55,  56.55,  71.55])

In [13]:
grade = []
for i in marks:
    if i>=95:
        grade.append('Grade A+')
    elif i>= 85 and i<95:
        grade.append('Grade A')
    elif i>=75 and i<85:
        grade.append('Grade B+')
    elif i>=60 and i<75:
        grade.append('Grade B')
    elif i>= 50 and i<60:
        grade.append('Grade C')
    else:
        grade.append('Fail')

In [14]:
grade_students = np.array(grade)

In [15]:
grade_students

array(['Fail', 'Grade C', 'Grade A+', 'Grade A+', 'Grade B', 'Grade A+',
       'Grade C', 'Grade A+', 'Grade A+', 'Grade A+', 'Grade A+',
       'Grade A+', 'Grade B', 'Grade A+', 'Grade A+', 'Grade A+',
       'Grade A+', 'Grade A+', 'Grade C', 'Grade B'], dtype='<U8')

# Q2. How to find the mean of every NumPy array in the given list?
The problem statement is given a list of NumPy arrays, the task is to find the mean of every
NumPy array.

In [16]:
lst = [np.random.randint(0,10,5),np.random.randint(0,10,5),np.random.randint(0,10,5),
      np.random.randint(0,10,5),np.random.randint(0,10,5)]

In [17]:
lst

[array([3, 2, 9, 1, 0]),
 array([3, 6, 7, 3, 0]),
 array([8, 5, 6, 4, 6]),
 array([2, 0, 0, 1, 3]),
 array([0, 7, 0, 0, 0])]

In [18]:
#mean of first array
np.mean(lst[0])

3.0

In [19]:
#mean of second array
np.mean(lst[1])

3.8

In [20]:
#mean of third array
np.mean(lst[2])

5.8

In [21]:
#mean of fourth array
np.mean(lst[3])

1.2

In [23]:
#mean of fifth array
np.mean(lst[4])

1.4

# Q3. How to multiply two matrices in a single line using NumPy?

In [25]:
arr1 = np.random.randint(0,25,25).reshape(5,5)
arr2 = np.random.randint(0,25,25).reshape(5,5)

In [26]:
#multiplication element wise
arr1*arr2

array([[138, 110,   6,  72,  90],
       [136, 208, 308, 308, 330],
       [117, 273, 143,  96, 231],
       [260,  27,  10,  19, 242],
       [154,  75, 552,  18,  92]])

In [27]:
#multiplication dot product
np.dot(arr1,arr2)

array([[ 564,  560,  705,  921, 1008],
       [1108, 1028, 1150,  790, 1747],
       [ 855,  755,  883,  532, 1388],
       [ 646,  395,  629,  611,  958],
       [ 588,  805,  677,  497, 1041]])

# Q6. How to add rows and columns in a NumPy array?
The problem statement is given a NumPy array, the task is to add rows/columns based on
requirements to the numpy array.

In [28]:
arr1

array([[23, 22,  1,  3,  9],
       [17, 13, 22, 22, 15],
       [ 9, 13, 11, 24, 11],
       [20,  3,  1, 19, 11],
       [ 7, 15, 23,  3,  4]])

In [29]:
np.sum(arr1,axis = 0)

array([76, 66, 58, 71, 50])

In [30]:
np.sum(arr1,axis = 1)

array([58, 89, 68, 54, 52])

In [31]:
arr1

array([[23, 22,  1,  3,  9],
       [17, 13, 22, 22, 15],
       [ 9, 13, 11, 24, 11],
       [20,  3,  1, 19, 11],
       [ 7, 15, 23,  3,  4]])

In [33]:
a = np.sin(arr1)

In [34]:
a

array([[-0.8462204 , -0.00885131,  0.84147098,  0.14112001,  0.41211849],
       [-0.96139749,  0.42016704, -0.00885131, -0.00885131,  0.65028784],
       [ 0.41211849,  0.42016704, -0.99999021, -0.90557836, -0.99999021],
       [ 0.91294525,  0.14112001,  0.84147098,  0.14987721, -0.99999021],
       [ 0.6569866 ,  0.65028784, -0.8462204 ,  0.14112001, -0.7568025 ]])

In [35]:
np.floor(a)

array([[-1., -1.,  0.,  0.,  0.],
       [-1.,  0., -1., -1.,  0.],
       [ 0.,  0., -1., -1., -1.],
       [ 0.,  0.,  0.,  0., -1.],
       [ 0.,  0., -1.,  0., -1.]])

In [36]:
np.ceil(a)

array([[-0., -0.,  1.,  1.,  1.],
       [-0.,  1., -0., -0.,  1.],
       [ 1.,  1., -0., -0., -0.],
       [ 1.,  1.,  1.,  1., -0.],
       [ 1.,  1., -0.,  1., -0.]])

In [37]:
np.rint(a)

array([[-1., -0.,  1.,  0.,  0.],
       [-1.,  0., -0., -0.,  1.],
       [ 0.,  0., -1., -1., -1.],
       [ 1.,  0.,  1.,  0., -1.],
       [ 1.,  1., -1.,  0., -1.]])