# 1. Create a 4X2 integer array and Prints its attributes

In [1]:
import numpy as np

In [20]:
arr = np.empty([4,2],dtype = np.uint16)

In [21]:
arr

array([[ 9256, 54062],
       [50219,  2436],
       [37784, 24049],
       [33611, 12818]], dtype=uint16)

In [22]:
arr_1 = arr.reshape(4,2)
arr_1

array([[ 9256, 54062],
       [50219,  2436],
       [37784, 24049],
       [33611, 12818]], dtype=uint16)

In [25]:
arr_1.dtype

dtype('uint16')

In [26]:
arr_1.shape

(4, 2)

In [27]:
arr_1.ndim

2

In [28]:
arr_1.itemsize

2

# 2. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [29]:
arr = np.arange(100,200,10)

In [30]:
arr

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [31]:
arr_1 = arr.reshape(5,2)
arr_1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

# 3. Following is the provided numPy array. Return array of items by taking the third column from all rows 
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])


In [32]:
samp_arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [33]:
samp_arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [34]:
arr_new = samp_arr[0:,2:3]

In [35]:
arr_new

array([[33],
       [66],
       [99]])

# 4. Return array of odd rows and even columns from below numpy array
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [36]:
samp_arr = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [37]:
samp_arr

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [38]:
arr_new = samp_arr[0::2,1::2]

In [39]:
arr_new

array([[ 6, 12],
       [30, 36],
       [54, 60]])

# Extract all odd numbers from arr
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:
#> array([1, 3, 5, 7, 9])


In [40]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = []
for i in arr:
    if i%2!=0:
        a.append(i)
print(a)

[1, 3, 5, 7, 9]


In [42]:
arr_new = np.array(a)

In [43]:
arr_new

array([1, 3, 5, 7, 9])

# Create a null vector of size 10


In [44]:
nul_ar = np.zeros(10)

In [45]:
nul_ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#  How to find the memory size of any array

In [46]:
arr = np.random.randint(2,10,5)

In [48]:
arr.size*arr.itemsize

20

# Create a null vector of size 10 but the fifth value which is 1

In [49]:
arr = np.zeros(10)

In [50]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
arr[4] = 5

In [54]:
arr

array([0., 0., 0., 0., 5., 5., 0., 0., 0., 0.])

# Create a vector with values ranging from 10 to 49


In [55]:
arr = np.arange(10,49)

In [56]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#  Create a 3x3 identity matrix

In [57]:
arr = np.ones(9)

In [58]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
arr = arr.reshape(3,3)

In [60]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#  Create a 3x3x3 array with random values

In [61]:
arr = np.random.random(27)

In [62]:
arr

array([0.49822992, 0.18299199, 0.0727874 , 0.83667226, 0.52667507,
       0.04671246, 0.00302358, 0.39828766, 0.6920244 , 0.2917414 ,
       0.82744617, 0.89051055, 0.34671117, 0.48737308, 0.62354526,
       0.91394071, 0.93529669, 0.7237692 , 0.37976035, 0.47146897,
       0.33064357, 0.8917944 , 0.80841126, 0.15234935, 0.4937175 ,
       0.83758508, 0.17530638])

In [63]:
arr = arr.reshape(3,3,3)

In [64]:
arr

array([[[0.49822992, 0.18299199, 0.0727874 ],
        [0.83667226, 0.52667507, 0.04671246],
        [0.00302358, 0.39828766, 0.6920244 ]],

       [[0.2917414 , 0.82744617, 0.89051055],
        [0.34671117, 0.48737308, 0.62354526],
        [0.91394071, 0.93529669, 0.7237692 ]],

       [[0.37976035, 0.47146897, 0.33064357],
        [0.8917944 , 0.80841126, 0.15234935],
        [0.4937175 , 0.83758508, 0.17530638]]])

# Print the numpy version and the configuration

In [65]:
np.__version__

'1.21.5'

In [67]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE