# 1) Write a program to iterate the first 10 numbers and in each iteration, print the sum of the current and previous number.

In [1]:
prev_num = 0
for i in range(0,10):
    sum_2 = prev_num + i
    print(f"sum of current number {i} and previous number {prev_num} is: ",sum_2)
    prev_num = i

sum of current number 0 and previous number 0 is:  0
sum of current number 1 and previous number 0 is:  1
sum of current number 2 and previous number 1 is:  3
sum of current number 3 and previous number 2 is:  5
sum of current number 4 and previous number 3 is:  7
sum of current number 5 and previous number 4 is:  9
sum of current number 6 and previous number 5 is:  11
sum of current number 7 and previous number 6 is:  13
sum of current number 8 and previous number 7 is:  15
sum of current number 9 and previous number 8 is:  17


# 2) Write a program to find how many times substring “Emma” appears in the given string.

In [2]:
str_x = "Emma is good developer. Emma is a writer"
n = str_x.count('Emma')
print(f'Emma appeared {n} times')

Emma appeared 2 times


# 3) Create a new list from a two list using the following condition
Given a two list of numbers, write a program to create a new list such that the
new list should contain odd numbers from the first list and even numbers
from the second list.
Given:
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]


In [4]:
list1 = [10, 20, 25, 30, 35] 
list2 = [40, 45, 60, 75, 90]
new_list = []
for i in list1:
    if i%2 != 0:
        new_list.append(i)
for n in list2:
    if n%2==0:
        new_list.append(n)
print(new_list)

[25, 35, 40, 60, 90]


# 4) Print downward Half-Pyramid Pattern with Star (asterisk)

In [6]:
n = 6
for i in range(n, 0, -1):
    for j in range(0, i-1):
        print('*', end = '')
    print('')

*****
****
***
**
*



In [7]:
n = 6
for i in range(0, n):
    for j in range(0, i-1):
        print('*', end = '')
    print('')



*
**
***
****


In [8]:
n = 6
for i in range(0, n):
    for j in range(0, i-1):
        print('*', end = '')
    print('')
n = 6
for i in range(n, 0, -1):
    for j in range(0, i-1):
        print('*', end = '')
    print('')



*
**
***
****
*****
****
***
**
*



# 5) Write a function called exponent(base, exp) that returns an int value of base raises to the power of exp.


In [10]:
base = int(input("enetr a number: "))
power = int(input('Enter another number: '))
b_p = base**power
print(f'{base} raise to power of {power} is: ',b_p)

enetr a number: 2
Enter another number: 5
2 raise to power of 5 is:  32


# 6) Write a NumPy program to test whether none of the elements of a given array is zero.

In [18]:
import numpy as np
arr = np.array([2,5,4,8,7])
arr ==0

array([False, False, False, False, False])

# 7) . Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [21]:
arr1 = np.zeros(10)
arr2 = np.ones(10)
arr3 = np.array([5,5,5,5,5,5,5,5,5])
arr = np.hstack(((arr1,arr2,arr3)))
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 8) Write a NumPy program to create an array of all the even integers from 30 to70.

In [22]:
a = []
for n in range(30,71):
        if n%2==0:
            a.append(n)
        else:
            continue
arr = np.array(a)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 9) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [23]:
arr = np.random.randint(10,25,15).reshape(3,5)
arr

array([[11, 15, 13, 19, 18],
       [22, 12, 16, 24, 19],
       [16, 20, 23, 19, 11]])

In [24]:
#sum of all elements
np.sum(arr)

258

In [26]:
#sum of each column
np.sum(arr,axis = 0)

array([49, 47, 52, 62, 48])

In [27]:
#sum of each row
np.sum(arr, axis = 1)

array([76, 93, 89])

# 10) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [29]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])